// Mocks generated by Mockito 5.2.0 from annotations
// in gastosrecorrentes/test/unit_test/view_models/bills_view_model_unit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:gastosrecorrentes/models/bill.dart' as _i4;
import 'package:gastosrecorrentes/services/remote/firestore_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FireStoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFireStoreService extends _i1.Mock implements _i2.FireStoreService {
  MockFireStoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> addBill(_i4.Bill? bill) =>
      (super.noSuchMethod(Invocation.method(#addBill, [bill]), returnValue: Future<dynamic>.value())
          as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> updateBill(_i4.Bill? bill) =>
      (super.noSuchMethod(Invocation.method(#updateBill, [bill]), returnValue: Future<dynamic>.value())
          as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> setBilltoInactive(_i4.Bill? bill) =>
      (super.noSuchMethod(Invocation.method(#setBilltoInactive, [bill]), returnValue: Future<dynamic>.value())
          as _i3.Future<dynamic>);
  @override
  _i3.Future<List<_i4.Bill>> getRegisteredBills({String? userId = r''}) =>
      (super.noSuchMethod(Invocation.method(#getRegisteredBills, [], {#userId: userId}),
          returnValue: Future<List<_i4.Bill>>.value(<_i4.Bill>[])) as _i3.Future<List<_i4.Bill>>);
}
